apiVersion: v1
kind: Service
metadata:
  name: consul-proxy
  labels:
    app: consul-proxy
spec:
  type: NodePort
  ports:
  - port: 8500
    targetPort: 8500
  selector:
    app: hashicorp-consul-server
